### ISSUE TITLE
Explain and maybe use a CONST instead of hardcoded literal

### ISSUE THREAD

**Issue by PKrause79** [mh-/corona-warn-companion-android#100]
https://github.com/mh-/corona-warn-companion-android/blob/488810fe381c9373fcc7864fef1f8ee69532b207/corona-warn-companion/src/main/java/org/tosl/coronawarncompanion/ramblereadout/RambleDbOnDisk.java#L71

"FROM devices WHERE service_uuids='fd6f'", null);

What is 'fd6f' for? Can you comment and refactor to a CONST? Thx very much

**Comment by mh-** [comment]
FD6F is explained here: https://www.google.com/covid19/exposurenotifications/ (see Bluetooth Specification).
("Exposure Notification is a Bluetooth Low Energy service registered with the Bluetooth Special Interest Group with 16- bit UUID 0xFD6F.")

Feel free to create a Pull Request.
