### ISSUE TITLE
publish new release for CCTG

### ISSUE THREAD

**Issue by p-p-1** [mh-/corona-warn-companion-android#102]
hey,

could you publish a new release, so we can use it with CCTG ([corona contact tracing germany](https://codeberg.org/corona-contact-tracing-germany/cwa-android)) ?

i had 7 low risk exposures and curious when they occurred ;)

thanks!

**Comment by corneliusroemer** [comment]
Was about to comment this on my previous related issue #101.

Thanks Michael for all the great work you're doing around CWA!

**Comment by mh-** [comment]
@p-p-1 Please see https://github.com/mh-/corona-warn-companion-android/releases/tag/2.0.4 and let me know whether it works. 
I cannot test this, since I don't use CCTG.

**Comment by p-p-1** [comment]
@mh- thanks for the fast reply and new release. unfortunately i am not able to install 2.0.4. version 2.0.3 can be installed though

**Comment by corneliusroemer** [comment]
There seems to be a build or signature error of some sort @mh- see #103

**Comment by mh-** [comment]
@p-p-1 @corneliusroemer Sorry about that. Could you please try again?

**Comment by p-p-1** [comment]
@mh- it's working now. thx.

**Comment by corneliusroemer** [comment]
Yes it works, can select CCTG.
