### ISSUE TITLE
APK of last release has broken signature

### ISSUE THREAD

**Issue by IzzySoft** [mh-/corona-warn-companion-android#103]
Can you please check and fix the APK attached to the latest release?

```
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
2020-12-14 19:30:57,538 ERROR: 
repo/org.tosl.coronawarncompanion_2000004.apk: 
2020-12-14 19:30:58,219 ERROR: Old APK signature failed to verify: repo/org.tosl.coronawarncompanion_2000004.apk

no manifest.

jar is unsigned.
```

Thanks in advance!

**Comment by corneliusroemer** [comment]
+1, I was just going to post that I can't install the apk, though I didn't get as neat an error message. 
Android 11, Oneplus8, Release 2.0.4 downloaded from Github

**Comment by mh-** [comment]
Strange. I did use a new Mac to generate this, but expected that the data transfer process yielded the same keys... Maybe some other mistake. Will try again.

**Comment by mh-** [comment]
Ok, I was able to reproduce the problem here, then built again, now it works - maybe I forgot to click a checkbox in Android Studio? ... Yes, I know, I should automate this.

**Comment by IzzySoft** [comment]
Yes, that looks good, @mh- – I just triggered the updater manually, and it happily munches the APK now. Will update the description as well, and then also trigger the sync so it becomes available in my repo ASAP.

As for your checkbox: most likely candidate is the "v1" signing checkbox – though then usually not even the Manifest is mentioned in the error message.

@corneliusroemer that message was produced by `apksigner verify --verbose <ApkFile>`, which is used by e.g. `fdroidserver`.

@mh- While on it: Would you be interested in a PR establishing [Fastlane structures](https://gitlab.com/snippets/1895688) in your repo, so you can maintain app description etc yourself from there on? I have that set up for my repo anyway, so I gladly provide it to you (including the screenshots if you wish – but those are then better "moved over" from `screenshots/` after merge).

**Comment by IzzySoft** [comment]
OK, [update available](https://apt.izzysoft.de/fdroid/index/apk/org.tosl.coronawarncompanion) now via my repo (i.e. also for those using the F-Droid client with my repo added to it).

**Comment by mh-** [comment]
@IzzySoft Yes I would be interested in Fastlane

**Comment by IzzySoft** [comment]
@mh- [there you go](https://github.com/mh-/corona-warn-companion-android/pull/104) :smiley:
