### ISSUE TITLE
Remove/reword "root required"

### ISSUE THREAD

**Issue by corneliusroemer** [mh-/corona-warn-companion-android#106]
Now with MicroG/CCTG v1.9, the companion app no longer requires root to work.

Would it make sense to make the "root required" warnings somewhat less prominent, or qualify them "root required for use with CWA, no root required for Ramble/CCTG export".

Some people understandably get confused now.

**Comment by mh-** [comment]
The thing is - how will these people not get confused by the words "RaMBLE/CCTG"?
CCTG itself is something that can't be easily found, nor installed through the Play Store, and mentioning the word "Corona" in the Play Store text is not an option either.

**Comment by corneliusroemer** [comment]
Up to you of course. Right now it's just not really correct. You risk putting off people who may benefit. Sure, one may think, who cares, if they checked out Github/read more they'd know better.
I don't know whether links work in Play store description, but you could place a link to this landing page somewhere: https://bubu1.eu/cctg/

Root is really rare out there. People are unlikely to have Ramble run significant amounts of time. So the biggest use case for the companion app has now become CCTG export. The companion app shows what is possible, but in order to get that, you need either root or CCTG. And CCTG is a matter of a few clicks. Even my parents figured out how to install it after I sent them the above link.

**Comment by mh-** [comment]
Well, I did update the Play Store text, readme, and so on. 
But I don't think that CCTG has that many users yet.
