### ISSUE TITLE
[Feature request] Allow import of CCTG/MicroG exposure.db from file, not just intent

### ISSUE THREAD

**Issue by corneliusroemer** [mh-/corona-warn-companion-android#107]
@tlambertz mentioned over at https://github.com/microg/GmsCore/issues/1328 that currently import of a saved exposure.db file isn't possible. The only way to use the exported database is to send it directly via Action/Intent from CCTG/MicroG to companion app.

It'd be cool if it was possible to import the database from the downloads folder, or some other appropriate place. Either via file picker or automatically, like the Ramble export gets imported.

**Comment by mh-** [comment]
In CCTG mode it should actually do what you are proposing, see #98 ?

**Comment by corneliusroemer** [comment]
I think we misunderstand each other.

I've saved the exposure.db to my download folder. Or sent it to you via email. How can we now investigate exposure stats without having it directly sent from within MicroG/CCTG?

I have a number of intent receivers for `.db` but the companion app isn't one of them. I tested it. Here you can see the apps which would accept the exposure.db file.

If I'm being stupid, let me know. I may have got something very wrong - but I can't see it.
![image](https://user-images.githubusercontent.com/25161793/102812342-239d5b00-43c7-11eb-8362-6aed8bdea1fb.png)

**Comment by mh-** [comment]
Looks like you would need to send is as mime-type `application/vnd.microg.exposure+sqlite3`, see https://github.com/mh-/corona-warn-companion-android/pull/97#issuecomment-746272831

At the moment, we already have two ways to import data from microG, I think we should try to reduce this to the one that's most convenient, not add another way.

**Comment by corneliusroemer** [comment]
Hmm, I'm not quite sure what you mean. How am I meant to set the mime-type? Shouldn't the companion app just accept the way the export file looks naturally?

Leaving rooted phones aside, there's only one way right now to get it from CCTG into companion, accept the export from microG settings.

All I'm suggesting is to accept the exposure.db not just from microG settings but the file in general, from any app. It's not really an extra way, it just means generalising the existing one to make it suitable for backups.

**Comment by anoadragon453** [comment]
As a user I also was confused by this. I exported the `exposure.db` from MicroG settings into my Downloads folder and then spent a while trying to figure out how to open it with this app.

Only stumbling upon this issue did I realise that I needed to open this app directly when exporting from MicroG.

While I think it would be nice if this app could simply pop open a file picker and choose the database file, I think it would also be nice to include some text telling users that they need to pick Corona-Warn-Companion when exporting the database from MicroG settings.

**Comment by mh-** [comment]
Unfortunately, I don't have a running microG setup*. I implemented microG support based on #57, and @tlambertz implemented the receiver for the export (#97), but I have never actually used it and don't know how obvious it is that you can "open the database with WAC" when exporting from microG.

*Technically, there's a microG included in CCTG, but I haven't found the export option in this scenario.

**Comment by anoadragon453** [comment]
MicroG will drop an `exposure.db` into a folder in `/sdcard`. I think we're just asking for a file picker in CWC to import it with.

**Comment by corneliusroemer** [comment]
@mh- I'm just using the CCTG bundled MicroG. You need version v1.9 upwards (you probably need the cutting edge Fdroid repo from Bubu, not the default one): https://bubu1.eu/cctg/

The export works by tapping on the ENF version number, then the MicroG settings open and you can export from there.

@anoadragon453  Exactly! Just a file picker in WAC to import an exposure.db - uncoupling the producer and consumer. While it's nice that one can do a direct export, it's not obvious and people may do exactly what you did, first saving, then trying to import.

@mh- I'm happy to help you figure out how to get CCTG up and running. My whole family is using it now, and with it your companion. I got my first match recently, from Ramble, when I drove on the highway.

**Comment by mh-** [comment]
![CCTG-export](https://user-images.githubusercontent.com/6257627/103066859-0086cd00-45ba-11eb-8508-41f232f90591.jpg)
This is how the export feature of CCTG looks on my device (now that FDroid has finally updated CCTG to version 1.9.1.6.
Honestly, it seems to be quite trivial to tap on the icon with the friendly dog?

I'm a bit more concerned that microG didn't collect RPIs during 2 days, while ENF did. In that respect, is it like RaMBLE? Do you have to constantly check whether it's running?

**Comment by anoadragon453** [comment]
> Honestly, it seems to be quite trivial to tap on the icon with the friendly dog?

It is, but the steps I originally took lead to confusion:

1. Get notified by my app that I have been close to someone with covid-19.
2. Go into MicroG settings to satisfy my curiosity.
3. Press 'export' and see a list of apps to share to.
4. Become confused why I can't just save the file, so I share to a messaging app and then save to disk from that app.
5. Look online for a way to analyse this exported database.
6. Find Corona-Warn-Companion. Download and Install it.
7. Spend a while trying to figure out how to open the database I exported with Corona-Warn-Companion.
8. Look in the bug tracker.
9. Figure out I need to share to Corona-Warn-Companion.

If there were just some instructions in the app to tell me to do step 9 I'd be happy. Adding a file picker would add more flexibility but it might not be necessary for most people.

**Comment by corneliusroemer** [comment]
@mh- You can get the newest builds directly from the CCTG repo (Fdroid has a weird week long delay): https://bubu1.eu/cctg/fdroid/repo/?fingerprint=f3f30b6d212d84aea604c3df00e9e4d4a39194a33bf6ec58db53af0ac4b41bec

No collection of RPIs for 2 days? Hmm, you seem to have a background activity problem then. Have you exempted CCTG from battery optimisation? What's your phone model? Maybe you can file an issue over at https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues ? I've never had an issue with CCTG running in the background. So it's important to hear reports with phone model, settings used etc. so we can try to figure out what happened and create fixes.

**Comment by ke352802081770314** [comment]
meanwhile, CCTG 1.9.1.4 made it into F-Droid repo (which seems to be the only way to download an apk file that I can install, I do not use the f-droid app so the beta path doesn't work for me, but that's a CCTG topic) so I immediately downloaded it.
Now I did just as shown above, exported to the Corona-Warn-Companion, it pops up immediately and tells me I must root to get exposures, just like before. I have CWC 2.0.5 which should be the current version, right? What am I doing wrong?

**Comment by mh-** [comment]
@corneliusroemer it's an Oukitel C16 Pro, Android 9.
Battery optimization has been disabled days ago for "Corona Tracing", but it simply doesn't collect RPIs. 
While RaMBLE and GAEN are active at the same time, and collect RPIs without any problems.

![Screenshot_20201228-085053](https://user-images.githubusercontent.com/6257627/103199164-87a1b100-48ea-11eb-8372-bb9ee4a77837.png)
![Screenshot_20201228-085105](https://user-images.githubusercontent.com/6257627/103199166-88d2de00-48ea-11eb-8e5a-f4963bf3a5fa.png)
![Screenshot_20201228-085116](https://user-images.githubusercontent.com/6257627/103199167-896b7480-48ea-11eb-88ce-d981612cc690.png)
![Screenshot_20201228-085328](https://user-images.githubusercontent.com/6257627/103199168-8a040b00-48ea-11eb-825a-724eac40726a.png)

After a re-boot, and re-start of CCTG, microG was apparently not available, CCTG didn't display anything about EN.
After killing CCTG twice, microG finally seems to start working now. Will check back later.

**Comment by mh-** [comment]
I think I have to manually start the CCTG app after a power cycle of the device, right?
But even then, microG doesn't immediately seem to start working, there's also no "currently used RPI" displayed. 
![Screenshot_20201230-132811](https://user-images.githubusercontent.com/6257627/103356594-87074700-4ab1-11eb-9379-1bd156273114.png)

I had to switch EN off and on again (on that screen), then it worked again.

**Comment by corneliusroemer** [comment]
Report it as a bug on Codeberg ;)

**Comment by wurstsalat3000** [comment]
An import feature for `exposure.db` would be very helpful when factory resetting your device/switching your device. A previously exported `exposure.db` could easily be imported this way.

**Comment by wurstsalat3000** [comment]
Since this is a valid use case for a friend of mine, I quickly put together an app feeding a local backup of `exposure.db` to Corona Warn Companion (using `application/vnd.microg.exposure+sqlite3` in a send Intent). An 'Import exposure.db' button would be easier though :)

**Comment by Tetrix42** [comment]
@wurstsalat3000 could you share the app?

**Comment by mh-** [comment]
A File Picker is implemented now for RaMBLE, because of the Android 11 Play Store policy.
Is this still interesting for your use case?

**Comment by IGNNE** [comment]
I found another use case for a file import: My daily phone only has 2GB of RAM, and with recent Android versions, it reliably runs out of memory trying to match the IDs. My first idea was to export my exposure.db to a friend with a better phone, and have them run the thing for me (or, alternatively, set up an Android emulator with plenty of RAM).

**Comment by xandro0777** [comment]
> Hmm, I'm not quite sure what you mean. How am I meant to set the mime-type? 

if desperately needed you could install one of the packages capable of intercepting intents - https://github.com/k3b/intent-intercept does that and allows you to resend the intent with edited mime types etc. In practice this might be tricky and require some trial and error.

However I think the feature would be useful enough that it should be supported out of the box.

I think it would be great if the app allowed the analysis of historical data - and that would require getting the data from files.

Also there might be circumstances where no internet is available to download the exposure data or a bigger device is needed to run the matching and in this situations it would be also very useful if the data could be loaded from a file.

**Comment by IGNNE** [comment]
I "fixed" my memory issues (#160) for now. Interestingly, the problem even ocurred in an emulator with 6GB of RAM, because of the heap limit. Weird, but I guess there are just too many Covid cases...
