### ISSUE TITLE
Switch from German official app (with root) to MicroG version does not work

### ISSUE THREAD

**Issue by AlphaDE** [mh-/corona-warn-companion-android#108]
I have the app in the current 2.0.6 version (Playstore) installed and have both the Playstore version of the official app using the Google framework and the MicroG version from F-Droid on my OP 7P with current firmware (+ Magisk 20.4).

The app works fine with the official app (using root), but switching to MicroG, I get a red warning that encounters cannot be read.

**Comment by mh-** [comment]
HI @AlphaDE,

According to #57 the microG database should be stored at `/data/data/com.google.android.gms/databases/exposure.db` 
Is that not the case in your setup?

With "the MicroG version from F-Droid" are you referring to CCTG, and its built-in microG?

Thanks
Michael

**Comment by AlphaDE** [comment]
Oops... ok, it's working, I assumed that the "MicroG" option is the CCTG F-Droid version. Your abbreviation pointed me to the right setting and it's working now. So I close.

**Comment by mh-** [comment]
@AlphaDE I’m confused by the many microG / CCTG options and versions as well. Especially because I only have Google Android devices, not Lineage or similar, so I cannot try that out myself. 

It would be helpful if you could briefly explain which setup works, and which doesn’t.

**Comment by AlphaDE** [comment]
@mh- I installed the CCTG version from F-Droid to replace the offical Play Store version.

The Companion from this project works with CCTG/F-Droid using the CCTG setting.

My error was, that I assumed I need to switch to "MicroG" because CCTG bases on that as far as I read... and that did not work.

So:

Companion works with Play Store version of the German Corona app with root

Companion works with F-Droid version of German Corona app (CCTG)

**Comment by mh-** [comment]
Ok, thanks.
I guess now I need to find out in which setup the "microG" setting might still be relevant - or if not, remove it.

**Comment by AlphaDE** [comment]
@mh- the CCTG settings works with the CCTG app from F-Droid, the MicroG setting does not.
