### ISSUE TITLE
y-axis values of "downloaded keys" get cut

### ISSUE THREAD

**Issue by schrolli** [mh-/corona-warn-companion-android#109]
Hi,

i have v2.0.6 installed. The main functionality is working great. Many thanks for creating this tool.

I have discovered a minor glitch with the y-axis marking of the second bar chart: the values get cut off at the left. I would suggest rounding that values to the next full thousands (36000 instead of 35999) and shorten that value by using a "k" suffix: 36k. Otherwise the y-axis must be moved more to the right, wasting up space for the charts.

![Screenshot_20201226-215042_Corona-Warn-Companion](https://user-images.githubusercontent.com/2263484/103159324-73fe2980-47c8-11eb-9b8b-f0fee10ec4e6.png)

**Comment by malloy139** [comment]
Numbers still get cut even on 2.1.1
![Screenshot_20210103-182556_Corona-Warn-Companion](https://user-images.githubusercontent.com/41596803/103484722-5268f780-4df1-11eb-9504-8bc75cd5c3e2.png)
