### ISSUE TITLE
Non root - use ramble log for calculations 

### ISSUE THREAD

**Issue by mzielinskim** [mh-/corona-warn-companion-android#11]
It would be nice to use ramble Bluetooth scanner Logfiles for users that don't have root. But i can log only the discovery uid andb8t would be nice to use your tool to compare the ids in the log to that on the warn app servers

**Comment by mh-** [comment]
Interesting, I will look into this. What exactly can you log, and what is missing?

**Comment by mzielinskim** [comment]
Anbei ein paar Infos:

https://www.chip.de/news/Corona-App-Bluetooth-Sniffer-spuert-Nutzer-auf_182782761.html

Die App: https://play.google.com/store/apps/details?id=com.contextis.android.BLEScanner&hl=en_US

https://www.un-hack-bar.de/2020/06/26/coron-app-nutzung-in-unna/

Die Scanergebisse kann man als SQLite-Datenbank ex/Importieren - zu den enthaltenen Feldern habe ich auf die Schnelle keine Doku gefunden. Ich kann aber einen Scan aufzeichen und exportieren um ihn zur Verfüging zu stellen.

**Comment by mh-** [comment]
@mzielinskim Does it work properly for you?

**Comment by mzielinskim** [comment]
Yes it works fine. Although it runs a while to find matches (yet I don't have matches in my ramble-Logfile)

Thanks for the instant implementation
