### ISSUE TITLE
different error message for "no access to exposure db" and "exposure db is empty"

### ISSUE THREAD

**Issue by ke352802081770314** [mh-/corona-warn-companion-android#110]
After upgrading CCTG to 1.9.1.4 I used the information sharing machanism and CWC (being invoked from the ENF sharing selection) reported (red) "FEHLER! Begegnungen konnten nicht ausgelesen werden. Sind Exposure Notifications eingeschaltet? Hast du dieser App ROOT-Rechte gegeben?"
when in fact it found an empty exposure database.
Repeating the same after some keys were found, it works.
I think I am not the only one eager to analyze immediately after installation, and the app should be able to distinguish between being able to read the database but it is empty, and failing to access it.
Therefore I think a different error message should be displayed when successfully accessing an empty database, to avoid confusing the user. Thank you.

**Comment by mh-** [comment]
Thanks for clarifying this, I will look into it.
