### ISSUE TITLE
Encounters cannot be read

### ISSUE THREAD

**Issue by mabli** [mh-/corona-warn-companion-android#111]
Hi,

I installed the Companion on a Sony Xperia XA2 with LineageOS 17.1-20201224-NIGHTLY-pioneer. Android 10. Open GApps ARM64 Pico is installed.  And the Corona Warn App is apparently running without problems. I have given the Companion Superuser rights via Magisk. In the Companion, however, I get a message that the encounters cannot be read. Same thing when I switch to RaMBLE mode (RaMBLE is installed and apparently runs without problems). What could be the reason for this?

Best Greetings 
Max

**Comment by mabli** [comment]
I have to say that I'm more of a user than a developer, but RaMBLE mode works now after I activated the UUID filter.
Do I have to set a special filter in the RaMBLE app? I still wonder why the exposure notifications from the Corona Warn app cannot be found in normal mode. Isn't it enough to give the app SuperUser rights? The Corona Warn App wouldn't function, if there were a problem with the Exposure Notifications, right!? So the problem must be the Connection between the warn app and the companion?

PS: Is there a more detailled documentation, how to set up the Companion?

**Comment by mh-** [comment]
With RaMBLE, you need to trigger an export in the RaMBLE app.
With Normal Mode, WAC looks into a specific file system location (which it can only do with root rights) to find the database. "Open GApps ARM64 Pico" apparently uses another location? Have you tries "microG mode", which looks in the location where microG stores the database?

**Comment by mabli** [comment]
RaMble works now. microG is the same: Begegnungen konnten nicht ausgelesen werden. Can i Change the file system location in GApps pico or is there a possibility that another package git the right path?

**Comment by mh-** [comment]
in microG mode, the database is expected here: `/data/data/com.google.android.gms/databases/exposure.db` - probably that's not where it is on your device?

**Comment by mabli** [comment]
It's propably a misunderstandig on my side. I have the regular CWA from Play Store installed. MicroG is used by the Corona Tracing App from F droid. Or am i wrong?

**Comment by mh-** [comment]
That’s correct

**Comment by mabli** [comment]
I thought about installing the Tracing App from F Droid, but in that case i would have to install microg and de-install GApps and that seems a little complicated :-p .  But am i right, that the WAC normally works with the regular CWA from Google Play Store?
And if so, is there a posibility to tell GApps or the WAC where to find the Exposure Notifications?

**Comment by mh-** [comment]
The official CWA gets data from an API. The Google EN framework offers this API. It also stores data in a place where WAC finds it. I don’t know what GApps does.
