### ISSUE TITLE
CCTG , no-Root, Android 11: Encounters cannot be read

### ISSUE THREAD

**Issue by elfrinjo** [mh-/corona-warn-companion-android#115]
As far as I understand, the combination of
CCTG, no ROOT access and this app should work. However, I keep getting the message:
"FEHLER! Begegnungen können nicht ausgelesen werden. Sind Exposure Notifications eingeschaltet? Hast du der App ROOT Rechte gegeben?"

Currently, I have both CCTG and the official app installed.

Device:
Pixel 4
Android 11
Security updates 05.12.2020
No ROOT access

Companion App: 2.1.0
CCTG: 1.9.1.6

**Comment by mh-** [comment]
In the CCTG app, you need to open the microG screen, and export the database from there. 
This is explained here: https://codeberg.org/corona-contact-tracing-germany/cwa-android#how-do-i-access-the-microg-exposure-notitifaction-settings-in-the-standalone-app

When you export the database, you can “share” it with this app - tap on the Friendly Dog icon. 
This works without root access.

**Comment by elfrinjo** [comment]
Thanks! I was under the impression that CCTG mode would do this by itselfs.
Maybe you could add a section about that to the readme and/or the error message.

Suggestion:

**CCTG mode - no root required**
This mode requires the installation of the alternative open-source corona tracing app from the [F-Droid Store](https://f-droid.org/de/packages/de.corona.tracing/) or [GitHub](https://codeberg.org/corona-contact-tracing-germany/). When installed, share the tracing information from CCTG to the companion as described in the [FAQ](https://codeberg.org/corona-contact-tracing-germany/cwa-android#how-do-i-access-the-microg-exposure-notitifaction-settings-in-the-standalone-app)

**Comment by mh-** [comment]
@elfrinjo Thanks for the suggestion, I extended the Readme: https://github.com/mh-/corona-warn-companion-android/commit/fe27680e98cf320df4c7195c0fb12f894bf49a89
