### ISSUE TITLE
Import all-exposure-checks.json

### ISSUE THREAD

**Issue by d00mfish** [mh-/corona-warn-companion-android#118]
I am not quite sure if this is possible but on android, it is possible to export all encounters from the Corona-Warn app as a .json called all-exposure-checks.json. Would it be possible to use this json as a source for the collected keys?

**Comment by mh-** [comment]
Unfortunately not, this file only contains a log, not the collected data itself.
You could e.g. use https://felixlen.github.io/ena_log/ to have a closer look what's in this .json file.
