### ISSUE TITLE
Automatically switches to Micro-G mode when launched from CCTG

### ISSUE THREAD

**Issue by hman2** [mh-/corona-warn-companion-android#119]
Hi,
I would like to pair Companion with Corona Contact Tracing Germany (CCTG). There is a CCTG mode available. I have learned that Companion won't find exposure data by itself, but can handle them when launched from CCTG with the dialog for export/share with Companion.

That does work. Partially.

Companion gets started and does get some data, but immediately switches to Micro-G instead of CCTG mode, and then displays just the diagnosis keys and risk contacts, if found, but not the other statistics that the demo screenshots show. Maybe this is due to the fact that Companion switches away from CCTG mode, even if set to this mode permanentyl, and into CCTG mode.

According to the devs of CCTG this would be a Companion issue, not one with CCTG...

Thanks
hman

**Comment by mh-** [comment]
CCTG uses the microG framework for the Bluetooth data collection, so both "CCTG mode" and "microG mode" use the same interpretation of the data.
* CCTG mode can be used if you have root access, then this app (WAC) can read the database from CCTG.
* The way you explain has to be used if there's no root access.

So you are using the correct mode, but could you please explain which statistics are missing? Maybe attach a (partial) screenshot?

**Comment by hman2** [comment]
Actually I COULD have root access, at least F-Droid can do so (with their own plugin to gain root access), as this is a Fairphone on Fairphone Open OS 19.11.2 (AOSP Android Nougat 7.1.2), that has an unlocked installer, but no "default" root privileges set.

In the menu of WAC, both Micro-G and CCTG are labelled "root".

The statistics I get in WAC are bar graphs with a) number of contacts, underneath that b) number of diagnosis keys downloaded, and then c) "risk contacts" (currently there are none). No graph about signal strength etc... 

Ah, I just tested the demo mode. There signal strength comes only after tapping a contact. So this could explain the situation, currently no risk contacts were identified...

**Comment by mh-** [comment]
Yes.

And the "microG mode" can be used if microG is installed, but not the CCTG app. Then WAC reads the microG database directly (needs root).

**Comment by hman2** [comment]
Suggestion for an improvement: Companion could remember which RPIs and diagnosis keys it has already compared. With 260101 diagnosis keys and 588 RPIs the process takes about 5 minutes each time Companion is launched (Fairphone 2, which is about lower midrange in performance)...

**Comment by mh-** [comment]
@hman2 yes, I'd like to implement this at some point in time, see #50
