### ISSUE TITLE
Add other country-specific Diagnosis Key download mechanisms

### ISSUE THREAD

**Issue by pdehaye** [mh-/corona-warn-companion-android#12]
It should be possible to adapt this to work with any exposure notification apps, not just CWA. That would involve adding different servers and logics to retrieve/use the keys. These logics are known, would you be interested to work on this?

**Comment by mh-** [comment]
The requirements will also evolve over time (e.g. the download server logic may change, or when a country switches to the GAEN v1.5 window mode, the relevant details for risk encounters might change). So this will involve some work in the future, tracking things like that.
I'm open to expanding the app for use in other countries, but would prefer if someone from the respective country contributes and commits to doing this tracking, the translations, and so on.

**Comment by pdehaye** [comment]
I don't have Android app experience (or even an Android phone), but I can happily explain to you how SwissCovid works (and do the tracking of how that evolves). What kind of process could you imagine to integrate this type of information the easiest?

**Comment by kbobrowski** [comment]
I'm quite interested in interoperability, @pdehaye I have implementation proposal in #24 which includes downloading Swiss DKs, feel free to check if the [logic is correct](https://github.com/mh-/corona-warn-companion-android/blob/4b7451e92bb4f09d10193f2300e6db04040cdfac/corona-warn-companion/src/main/java/org/tosl/coronawarncompanion/dkdownload/DKDownloadSwitzerland.java)

**Comment by pdehaye** [comment]
That's great, @kbobrowski ! It looks like the logic works! The most important point for CH is that the files at a specific URL change, more TEKs get added over time in "older" file. The timestamp in the filename represents validity of the TEKs contained in that file (so one infected individual's TEKs get split over many files). 

So for CH you can't tell yourself (unlike for other countries) "I have downloaded that file before, no longer need to" (can you confirm that's not what you are doing?).

**Comment by kbobrowski** [comment]
@pdehaye this should work fine, will always download all timestamps

**Comment by pdehaye** [comment]
As @mh- already pointed out, maintenance is likely to be a problem long term, so it would be good habit maybe to instill to document a bit with text the assumptions made on how the server delivers the keys. In case the server delivery method changes, it will then be easier to assess what needs to be done.

**Comment by uhengart** [comment]
I have written some code to download Canada's diagnosis keys: [retrieve-canadian-diagnosis-keys](https://github.com/uhengart/retrieve-canadian-diagnosis-keys). Would you be interested in integrating the code? I would do it myself but I'm not familiar with ReactiveX.

I have used this code to download Canada's diagnosis keys on an hourly basis to estimate the number of infections reported through our app ([covid-alert-dashboard](https://github.com/uhengart/covid-alert-dashboard)) so am pretty familiar with the Canadian server and could answer questions about it.

**Comment by kbobrowski** [comment]
@uhengart thanks for providing implementation, I will copy it here

**Comment by mh-** [comment]
#58 merged.

**Comment by uhengart** [comment]
I have a feature request for Canada. 

I noticed yesterday that the LAST_14_DAYS_PERIOD period value that is currently used in the implementation returns the keys uploaded on the last 14 days but not the keys uploaded today. 

To also download today's keys, a second download is required, with the period value set to System.currentTimeMillis() / 1000 / 3600 / HOURS_PER_PERIOD (see https://github.com/uhengart/retrieve-canadian-diagnosis-keys/blob/master/DetermineDiagnosisKeysURL.java). 

Could you please add this second download? Thanks.

**Comment by mh-** [comment]
@uhengart I created #63 for this. It should be fixed now.

**Comment by uhengart** [comment]
@mh- Thanks! It's working.

**Comment by mh-** [comment]
As there are many additions via the [EU Federation Gateway Service](https://github.com/eu-federation-gateway-service/efgs-federation-gateway) now, I think we can close this.
