### ISSUE TITLE
Feature request: histogram with the signal strength of all contacts

### ISSUE THREAD

**Issue by timkalkus** [mh-/corona-warn-companion-android#120]
This is a bit inspired by issue #77, but with a solution how to give the user some valuable data without violating anyone's privacy (because privacy concerns where the stated reason why the other issue was closed):

A histogram of the signal strength generated from all contacts. 

This can be a helpful tool to understand how the signal strength on the own device varies and will give some context to the signal strength of positive contacts. And because in the histogram all data is contained and the time information is lost, you can't trace this information back to individual encounters. So there should be no privacy given away.

And a quick example from myself how this could help the user:
The free positive contacts I had were all with a signal strength of around -70 to -80 dB. Without additional context one can't be sure if such result is from a great distance between the phones or if e.g. the phone itself is shielding a lot of the signal resulting in such low values.

**Comment by jmichler** [comment]
I agree that this would help. I disagree though why #77 is a privacy issue. There are way more privacy issues when allowing to drill down into positive contacts - which is probably the main feature of the app compared to the official one - aren't there? What harm is caused through showing when and how strong tokens where received?

**Comment by mh-** [comment]
Privacy is always about trade-offs, and in my opinion, the good reasons to drill down into matches outweigh the perceived privacy risks. 

This does _not_ hold for non-matches. And I do not want to create a replica app of this: https://www.n-tv.de/technik/AfD-verkauft-unnuetze-Spaeher-App-article21901375.html
The article also explains the limitations of non-matches:
For non-matches, you can only see the strength of the reception (RSSI), not the strength of the transmission (TX Power) which is encrypted and can only be decrypted in case of a match. This TX Power varies significantly between phones (see TX in the .csv table provided at https://developers.google.com/android/exposure-notifications/ble-attenuation-overview)

The relevant information is the _attenuation_ (== RSSI - TX Power), which is not available for non-matches.

**Comment by timkalkus** [comment]
By (naively) looking at the raw distributions of TX-Powers listed in that file, you may assume that "most" devices have an TX of about -25. Of course to get a more realistic impression of the actual distribution, you'd need to know which phone was sold how often. 
But maybe this approach is accurate enough to get a somewhat correct histogram of the receiving strengths (because you'd include the data of all recieved keys)?

![TX_Distribution](https://user-images.githubusercontent.com/24697274/106645674-f67ac580-658c-11eb-8052-b70c6c1155a9.png)

**Comment by ke352802081770314** [comment]
I am puzzled about the large number of contacts recorded in some environments, for example when alone in my apartment, and the phone is on the bedside table, I have 23 IDs in the last hour. It would be reassuring that they are at very low strength because there is not only several meters distance in any direction to possible other people but also brick building walls (sideways) or floor/ceilings (vertically) separating me from anyone else, so from the perspective of exposure, no contact is happening at all. Why would I collect more IDs when isolated at home than when I go to the supermarket? Seeing stronger signals in the public setting would certainly be reassuring.
Statistics: OnePlus 3, LineageOS(Android 9), CCTG with built-in ENF (no separate MicroG installation).

**Comment by mh-** [comment]
As the IDs change every 10 minutes, you apparently have 4 neighbours (or one with 4 devices) who transmit these IDs. Using BLE apps, like RaMBLE, or nRF Connect, you can have a look at the strength of these signals.
