### ISSUE TITLE
Dark Mode Toggle in CCTG

### ISSUE THREAD

**Issue by Feuerswut** [mh-/corona-warn-companion-android#122]
Please add a toggle to overwrite the system-wide dark mode in all versions.

**Comment by fynngodau** [comment]
> in CCTG

You meant the companion app that this repo is for, not Corona Contact Tracing Germany, right?

**Comment by Feuerswut** [comment]
> > in CCTG
> 
> You meant the companion app that this repo is for, not Corona Contact Tracing Germany, right?

Both?

**Comment by fynngodau** [comment]
@Feuerswut If you want to discuss this for CCTG you’ll need to use our CCTG issue tracker at https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues.
