### ISSUE TITLE
High transmission risk with just one contact with high distance

### ISSUE THREAD

**Issue by fakerli** [mh-/corona-warn-companion-android#123]
It shows a high transmission risk of 7 (out of 8) but the contact was just once and with a high attenuation. The official app doesn't even recognize it as a contact.

![CEAA376B](https://user-images.githubusercontent.com/12958497/112613168-178ac480-8e20-11eb-9fcb-2b44f3678ede.PNG)

**Comment by mh-** [comment]
The field "transmission risk" relates to the person who uploaded the Diagnosis Key. 
It's good that you didn't come close to that person, and not for long, so your personal risk was probably low. That's also why the official CWA didn't show it.
