### ISSUE TITLE
RaMBLE is no longer available in the Play Store

### ISSUE THREAD

**Issue by FinnHuelsbusch** [mh-/corona-warn-companion-android#126]
RaMBLE is unfortunately no longer available in the Play Store. 
Is there an alternative that is compatible with the app? 
If not please point this out in the documentation.
I hope that this is the correct place to point this out... 

Kind regards 
Finn

**Comment by mh-** [comment]
You could download RaMBLE from one of the APK mirror sites like https://apkpure.com/de/ramble-bluetooth-le-mapper/com.contextis.android.BLEScanner , but obviously, installation will not be as convenient as using the Play Store.

If you use F-Droid, you could install this app: https://f-droid.org/de/packages/de.corona.tracing/ 
However the functionality and handling is completely different from RaMBLE.

**Comment by Ein-Tim** [comment]
@mh- I think it would make sense to remove the dead link to the app from the README.md.
