### ISSUE TITLE
cwcompanion shows risk enc. cctgermany doesnt

### ISSUE THREAD

**Issue by skyerjoe** [mh-/corona-warn-companion-android#127]
Xiaomi mi9t pro ( no root ) 
Android : mui 12.0.5 based on Version 10  QKQ1.190825.002
corona warn Companion: 2.1.1
Corona contact tracing germany: 2.1.2.2

Mode:  export from cctg to cwc 

Cwc:

![Screenshot_2021-05-16-09-07-44-749_org tosl coronawarncompanion](https://user-images.githubusercontent.com/1038130/118389202-004ea300-b629-11eb-8fed-fe0084db7c2b.jpg)

Cctg:

![Screenshot_2021-05-16-07-30-45-780_de corona tracing](https://user-images.githubusercontent.com/1038130/118389214-16f4fa00-b629-11eb-8c88-580177dc4f81.jpg)

So which one produces the false result , any clue ?

Best regards

**Comment by mh-** [comment]
Both apps make a correct statement: CWC shows you a match (short and high attenuation - so likely with a large distance), and CCTG shows you "no significant risk".

Please note that CWC is not trying to make a risk calculation, it only shows you raw matching data. The idea is that you use CWC mainly when you got a warning by CCTG or CWA and want more raw details.

**Comment by skyerjoe** [comment]
Ok
I thought it was an misinterpration  from one of the apps
But why is the risklevel  for the encounter so high (8) ?  
Best regards

**Comment by mh-** [comment]
Sorry for the misunderstanding, the Transmission Risk Level shown does _not_ belong to the specific encounter, but only to the other person (who transmitted the beacon that was now matched). It means that on that day, this person was very infectious. So - Good that you apparently did not come close. 

Here's some more explanation: 

https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf

**Comment by skyerjoe** [comment]
No worrier
Is the transmission time  from the beacon which is showed in the app in realtime or do I have to use an small time frame intervall (ex. 5-10 min. ) for guessing the real encounter time.

Best regards

**Comment by mh-** [comment]
The timestamp is the exact timestamp when the beacon was received. Your microG framework does not scan each and every second, though, so the beacon could have been in range before or after that timestamp as well.

The screen shot above shows 100dB attenuation, which is typically classified as "pretty far away". 100dB is the difference between `RSSI_measured` (the received signal strength measurement on your device), and `TX_power` (what the sending device included as the transmission level). You can read more about this here: https://developers.google.com/android/exposure-notifications/ble-attenuation-overview (and for completeness: CWC does _not_ add any `RSSI_correction`, it does not attempt to guess which phone you are using and does not look up any correction value).

https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md also explains the translation between attenuation and risk that CWA (and CCTG) use.

**Comment by skyerjoe** [comment]
so if  i understand that correct , the following situation should be possible:

the infected person with the certain beacon is at first really close to me, then after 3-4 minutes i went away, 2 min. later, cwa or cctg scans the environment and catches the beacon and says it's really far away. 

so the app misssed the keypoint with the first close contact.

am my assumptions right ? 

best regards

**Comment by mh-** [comment]
This is a possible scenario, and a consequence of the fact that BLE scanning is an expensive operation in terms of battery consumption. 

If you wanted a system that permanently scans, you could build that, too (e.g. MicroG is open source, you should be able to modify it), but you'd need a large battery.

**Comment by fynngodau** [comment]
Additional info: microG scans every 3 minutes, which is more frequent than Google Play services already (https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/23).

**Comment by skyerjoe** [comment]
what about google nearby messages api  ? 

i havent found any documentaion for scan intervall or sth like that.  

btw. stop corona app  from austria is using this api
especially the ultrasonic feature may be useful for cwa too, but as far as i know the enf  api doesnt support this. 

best regards

**Comment by skyerjoe** [comment]
Moreover 
Is it possible to repoduce or simulate  some Encounters Situations  like these with an ble scanner like ramble or beacon scope  with 2 devices ? 
That the value is close similar to an value which is measured  by the cctg or cwa app ?  
So that i can create  a more  tangiable picture , how risky the situation was.  


Best regards

**Comment by skyerjoe** [comment]
Ok ive found an interesting pic which describes the intervalls missings with Bluetooth in easy way

https://github.com/corona-warn-app/cwa-documentation/blob/master/images/solution_architecture/figure_14.svg

For the other thing ive found some info and its solves my question so i closing this issue   

Best regards
