### ISSUE TITLE
OutOfMemoryError while opening exposure.db from CCTG

### ISSUE THREAD

**Issue by pjaap** [mh-/corona-warn-companion-android#133]
Hi since today the app crashes one minute after I export the exposure.db from the CCTG app. Yesterday everything was fine.
I captured the moment in ADB logcat. I have 5400 tokens. I that too much?

Restarting the app, the phone had no effect. 

[log.txt](https://github.com/mh-/corona-warn-companion-android/files/7571434/log.txt)

**Comment by mh-** [comment]
Obviously that's a good first assumption - the list seems to be too big. 
I would like to try and replicate this, but don't have large test sets, so if you could send me the database - I would promise to not publish it and delete it after debugging.

**Comment by pjaap** [comment]
Sure, I'll dm you the database. I just tested and still reproduce the problem. I checked some more combinations  and found out that it works using only the Austrian database for checking the tokens. Maybe the default server data (Germany, Denmark, etc) is (nowadays) too big?

I use a Samsung A3 2016 (a3xelte) with official LineageOS4MicroG. I guess the 1.5 GB of RAM is the problem. On a friends phone with >3GB RAM (also LOS4MG) there is no problem. Restricting background processes etc did not help. TOP reported a 25% RAM usage peak for your app just before the crash. Maybe this helps.

**Comment by mh-** [comment]
Thanks for sharing the database.
On my Oukitel C16 (3GB RAM) this works: ~5k encounters, ~800k Diagnosis Keys, and matching works as well.
Now how to solve this... Obviously, one strategy could be to read only half of the database, handle it, then read the other half and handle that. But at first glance, I don't even know how to decide how much RAM is sufficient, what size fits into it, and so on...

**Comment by mh-** [comment]
Another option might be to process the download keys sequentially, i.e. download one file, do the matching, then the next. This may slow everything down, though. Maybe another option for the user to select? But if the app crashes immediately, a user selection isn't that easy either...

**Comment by pjaap** [comment]
Thanks for looking into this. And don't know how much effort it would make to change the way the matching is done. Matching the packages day-by-day sounds promising to me. I you provide a test apk I will happily test it on my device.

**Comment by vanMacG** [comment]
I have a Samsung S5 (klte) with 2GB RAM and ran into the same problem (just for the records: lineageos with microg and cctg).
For historical reasons I had following country-sets activated: "Austria", "Germany, Denmark, ..." & "Switzerland". My own encounters show up but when downloading the country-sets the app crashes.

What I did as a "workaround":
- Deactivate Wifi and mobile data (so the app doesn't crash immediately on launch)
- Uncheck Austria and Switzerland in the country-set list
- Reactivate Wifi and mobile data
- --> Download and matching works again.

**Comment by pjaap** [comment]
Since today using the Austrian database results also in a crash. Seems like it is now also too big.

**Comment by pjaap** [comment]
Hi. I just updated to 2.1.3 today and the issue is gone for me. Thanks!!!
