### ISSUE TITLE
Hangup/crash with Austrian RPI

### ISSUE THREAD

**Issue by hman2** [mh-/corona-warn-companion-android#134]
This issue report corresponds with the same report in CCTG (https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/202)

Today I was in Austria and had CCTG running. Now it spends endless minutes checking recorded contacts, and finally it crashed.

I exported the data into Corona Warn App Companion. It has a feature to activate/deactivate certain countries. With Austria disabled, it runs the check. With Austria enabled, it also hangs endlessly and eventually crashes.

So I make a wild guess: Something is wrong with whereever both apps download diagnosis data from Austria. That source could be down or disturbed. But even if that is the case, apps must never hang or crash, they should exit gracefully with an error message, IMHO.

Also, it would be helpful if an updated version of Companion could be released that does not constantly reload diagnosis data that has already been downloaded previously. Now that we have almost a million diagnosis keys, some way shape or form of load reduction is necessary, and IMHO the first move could be to only download and process new keys... Often, companion simply quits. Sometimes it's just the screensaver/lock screen kicking in (Android 9), and when Companion gets fullscreen again, it starts to download all keys anew...

Thanks
hman

**Comment by mariow** [comment]
I can confirm the very same issue on my device (Oneplus 9 Pro running Android 11): activating the Austria list always leads to a crash of the companion app.

Just for fun I tried installing Android Studio and importing the source code there. A fresh setup of the code with a Pixel 5 virtual device shows the exact same behavior. The app runs fine until I activate the Austrian list. If I understand the output correctly (I haven't worked with java for two decades) the code runs into an OOM error.
Is it possible that the Austrian list is way bigger than the German one?

**Comment by hman2** [comment]
Given the smaller number of Austrian citizens I would doubt that. Also, the 7 day incidence is currently (slightly) lower in Austria, compared to Germany.

**Comment by mariow** [comment]
Digging a bit deeper it seems that the Austrian file contains all keys for the last 14 days while the German export has one file per day. That's why the Austrian file looks bigger - there are several downloads that get combined for Germany.

In any case this is the max I'm able to find out here with my limited Java knowledge. I hope someone with more experience is able to look into this.

**Comment by mariow** [comment]
Unfortunately #139 did not solve the issue for me, activating the Austrian list still results in a crash.

**Comment by mh-** [comment]
Please note that the "Germany+Europe" data includes the Austrian data, so it might be a workaround to select "Germany+Europe" instead.

**Comment by skyerjoe** [comment]
I tried to reproduce the Crash but it seems working.

But sth else is curious i have  13 matches with the db from austria but atm im in Germany.
Is that normal ?

**Comment by mh-** [comment]
The Austrian database (which is used for the Austrian Stopp-Corona App) also contains German data. See https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_en
