### ISSUE TITLE
Companion won't download diagnosis keys for dates where no RPIs have been recorded

### ISSUE THREAD

**Issue by hman2** [mh-/corona-warn-companion-android#135]
I use Companion together with CCTG.

For unknown reasons, CCTG stopped recording RPIs after Dec. 16. I can see the total lack of RPIs both within CCTG and the Companion. But what's strange is this:

Companion won't download diagnosis keys for dates where no RPIs where recorded. While it is pefectly plausible (although somewhat less likely) that on one given date no RPIs were recorded. It is also perfectly un-plausible that on any date there would be no diagnosis keys, but that is what Companion shows me. 0 downloads on dates where 0 RPIs were recorded...

Thanks

**Comment by mh-** [comment]
The [intended behaviour](https://github.com/mh-/corona-warn-companion-android/blob/d3ebabb39bb1c2f552024861ab3e774670884db8/corona-warn-companion/src/main/java/org/tosl/coronawarncompanion/MainActivity.java#L438) is to look up the first day where RPIs were recorded, and then download keys from that day onwards.

**Comment by hman2** [comment]
I does indeed start with the first day where RPIs are in the DB that CCTG passes on. But definitely, NO keys are downloaded after Dec. 17 to present. Dec. 16 is the last day that CCTG recorded RPIs (for whatever, unknown reason). 

I companion, I now have 11 bars with encounters and 11 bars with keys...

**Comment by mh-** [comment]
Well, there's similar code for the last day where RPIs were recorded: https://github.com/mh-/corona-warn-companion-android/blob/d3ebabb39bb1c2f552024861ab3e774670884db8/corona-warn-companion/src/main/java/org/tosl/coronawarncompanion/MainActivity.java#L440
That seemed to be a simple way to determine the time window of interest.

**Comment by hman2** [comment]
But since the last recorded RPI can be older than 0-1 days, and even on days without RPIs there will surely be diagnosis keys, why not use the current date as last date? There cannot be diagnosis keys coming from the future (unless there is an error), so I think it would be safe to download and process keys from first date to present day...

**Comment by mh-** [comment]
I guess I thought that processing keys for days on which a match isn't possible wouldn't be required.

**Comment by hman2** [comment]
Why could a match not be possible?

An RPI gets recorded on day 1. The owner of the sending phone could then get a diagnosis on any later day. Of couse there shouldn't be much delay to the date of testing, but the diagnosis (especially if PCR) can take several days after the proble sampling was done. PCR can take 10 days or more... So the owner of a sending RPI can report being tested positive several days later... Possibly even on day 14 or 15...

**Comment by mh-** [comment]
Of course the Diagnosis Keys will be downloaded later. They have a validity period (which is in the past), and matching with the recorded RPIs only makes sense for that validity period.
CWC does not show how many DKs were _downloaded_ on a particular day, but how many DKs were _valid_ on that day.

**Comment by hman2** [comment]
I find it very hard to believe that NO DKs were valid immediately after CCTG stopped recording RPIs... The total number of downloads also shows that significantly fewer DKs were downloaded...

**Comment by mh-** [comment]
> I find it very hard to believe that NO DKs were valid immediately after CCTG stopped recording RPIs... 

While there were many DKs available for download which are valid on the next day, they were not relevant, because you didn't have recorded any RPIs on that day that could be used for matching.

But it looks like it started working per your expectations again.

**Comment by hman2** [comment]
"While there were many DKs available for download which are valid on the next day, they were not relevant, because you didn't have recorded any RPIs on that day that could be used for matching."

I do not understand why the RPIs recorded on PREVIOUS days (before recording stopped) should be irrelevant? A diagnosis can take up to 14 days (if PCR).

This leads me to this conclusion: If at least 1 RPI get recorded in the 14 day period, then on ALL 14 days ALL diagnosis keys MUST be downloaded. Days without downloads are ALWAYS an error.

Correct me if I'm wrong. But unless CCTG does this (currently it doesn't) or you convincingly explain where I made a logic error, then I do not consider this issue resolved.

**Comment by hman2** [comment]
Let me explain my logic in a made-up example scenario:

On day 1 I happen to be in the vicinity of User X, and my phone records an RPI from user X.

On day 2 due to some error, my CCTG stops recording FURTHER RPIs, so I miss the RPIs from users Y and Z from day 3 and 4.

On day 5, user X gets a positive diagnosis, and he faithfully shares this with his CWA, so all the RPIs he sent out will be marked as incounters with positively testet covid infected users.

But I do not get this from Companion, because companion discarded all diagnosis keys from day 5 as "irrelevant"... !

Can you follow my logic? This is why I believe Companion must load all diagnosis keys if the number of RPIs within a fortnite is greater than 0...

**Comment by mh-** [comment]
> On day 5, user X gets a positive diagnosis, and he faithfully shares this with his CWA, so all the RPIs he sent out will be marked as encounters with positively tested covid infected users.

This user will send up to 14 Diagnosis Keys to the CWA server, one for each of the previous days. Those 14 keys will be in the daily download of day 5. Only 2 DKs out of these 14 keys (from day 1 and day 2) in your scenario can match recorded RPIs.   12 keys can safely be discarded, because they belong to days on which you have not recorded any RPIs, so a match is not possible.

**Comment by hman2** [comment]
I still don't understand your logic. "This user will send up to 14 Diagnosis Keys to the CWA server, one for each of the previous days. Those 14 keys will be in the daily download of day 5."

On day 5 Companion won't download anything, because on day 5 (in this scenario) also no RPIs were recorded. At least this is my interpretation of the missing bar on day 5... So do you want to say that on day 5 diagnosis keys are in fact downloaded, but only being represented in the bar of the corresponding day?

Also, I have now (that the gap in recording moved to the beginning of the 14 day period) observed, that the same scenario happens if there is a gap at the beginning of the RPI data. This also leads to less than 14 bars. Today I have noticed (I still record RPIs from my neighbour in the flat one storey below) that a bar for the current day won't appear until my neighbour started into his day (by switching on his cell phone. Really, this should teach us all a lesson in data privacy: Simply by looking at the RPIs I can tell the hour when my neighbour belowe wakes up, and I can tell on what days he was on vacation...!).
