### ISSUE TITLE
Warn Companion crashes when exporting data from CCTG 

### ISSUE THREAD

**Issue by NightbotLeL** [mh-/corona-warn-companion-android#140]
Hello,
![Screenshot_20220105-120923_Corona Tracing](https://user-images.githubusercontent.com/64130599/148208399-5ea99bae-1f81-448d-8bd0-fbafaef306fc.jpg)
![Screenshot_20220105-121004_Warn-App-Companion](https://user-images.githubusercontent.com/64130599/148208403-e17953a8-d41f-45f5-939e-968b651954eb.jpg)
![Screenshot_20220105-121020_Corona Tracing](https://user-images.githubusercontent.com/64130599/148208404-0fc26d8f-dc8d-4d9c-9254-7d836a4c8a8d.jpg)
 when I export data from CCTG Vers. 2.14.1 to Warn Companion, Warn Companion crashes. There is no error message and I am always kicked out to the CCTG App. 

Device: Samsung Galaxy A51
Mode: MicroG
OS: Android 11
App: From Google Play

**Comment by DerVogel2020** [comment]
Related to #137.

**Comment by NightbotLeL** [comment]
> Related to #137.

Yes
