### ISSUE TITLE
The app crashes when there are many risk encounters and the details for these encounters are viewed

### ISSUE THREAD

**Issue by NightbotLeL** [mh-/corona-warn-companion-android#142]
Hello, I currently have 59 risk encounters and would like to analyze the data, if I click on a day and scroll a bit, the app kicks me out and i go in CCTG.

**Comment by mzielinskim** [comment]
I also have that problem when selecting a day and scrolling sometimes on days with several entries the app crashes and shows a white screen. im using Ramble mode. when scrolling i always enable the maps to see where i was at that time.

**Comment by NightbotLeL** [comment]
Hello, im Using MicroG Warn. if I go on days then unfortunately it crashes. That only happens to me when I go on days where I had a lot of risk encounters

**Comment by r00t-** [comment]
i'm also seeing crashes during analysis.
this appears to have started with the new year (at least i did not install any updates or anything like that, and never saw a crash in december).
it appears to be related to the reliability of the network connection? it appears that i see more crashes when on a low-quality network connection, when i tried on my home wifi it suddenly worked.m
i looked at logcat, and everytime it seems the process is killed due to out-of-memory. (attaching an example.)
[Uploading oom_22:24.txt…]()

**Comment by Dani4u2** [comment]
![Screenshot_20220107-174908](https://user-images.githubusercontent.com/97305371/148578913-ddb7a337-6f30-493a-aebd-35f8a66f39f2.png)
Seit heute dieses Problem. Bis gestern lief alles wunderbar.

**Comment by mh-** [comment]
@Dani4u2 Verwendest Du Android 11? Dafür gäbe es inzwischen eine Lösung.

**Comment by mh-** [comment]
For the problem where the app crashes because of out-of-memory when showing days with many encounters - it would help me a lot if someone could send me a database that reproducibly crashes.

**Comment by Dani4u2** [comment]
Ja Android 11.

Bis gestern Null Probleme damit gehabt

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mh-** [comment]
@Dani4u2 Das Problem und die Lösung ist hier beschrieben: https://github.com/mh-/corona-warn-companion-android/issues/143 
Release 2.2.0 wird gerade für den Play Store "überprüft", und es gibt sie auch hier auf Github,

**Comment by Dani4u2** [comment]
Super! Das war die Lösung! Tausend Dank 🍀

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mzielinskim** [comment]
Für den Bug beim scrollen durch die Anzeige der Kontakte eines Tages ist die neue Version keine Fehlerbehebung. Das tritt weiterhin auf (bei mir bisher wenn ich mehr als 5 Kontakte hatte und die Karten aktiviert habe. Nach ein bisschen scrollen wird der Bildschirm komplett weiß und nichts passiert mehr...

**Comment by mh-** [comment]
Hmm, tja, ich versuche noch, das zu reproduzieren, aber schaffe es noch nicht. Ich bräuchte so eine Datenbank, bei der die App immer abstürzt...

**Comment by mzielinskim** [comment]
Ich habe dir meine DB geschickt für die Analyse.

**Comment by mh-** [comment]
Ok, vielen Dank!

**Comment by mh-** [comment]
Closed with https://github.com/mh-/corona-warn-companion-android/commit/3611e8001e30d33086cdc87ffc574bdc2ce485de
