### ISSUE TITLE
Android 11: RaMBLE data cannot be read.

### ISSUE THREAD

**Issue by Clysa** [mh-/corona-warn-companion-android#143]
Hi, ich habe seit Monaten auf einem Android11-Phone den WAC im RaMBLE-Modus laufen. Funktionierte bis vor einigen Tagen gut, dann crashte das Programm immer bei dem Versuch, Schlüssel und Begegnungen runterzuladen. Hab dann, nachdem ich hier einiges über das Problem gelesen hatte, die Version 2.3.1 installiert. Die crasht nicht, liefert aber jedes Mal die Fehlermeldung "Begegnungen können nicht ausgelesen werden.´" und fragt, ob ich der App erlaubt habe, auf Dateien zuzugreifen (hab ich) und ob ich eine RaMBLE-DB exportiert habe. Ja, hab ich, genauso wie in den Monaten zuvor. Die DB landet am üblichen Platz im Download-Ordner und hat eine Größe von über 60 MB, kann also auch nicht leer sein. Was läuft hier falsch? Freu mich über jeden Hinweis!

**Comment by mh-** [comment]
Hallo, 
das ist leider im Moment ein ungelöstes Problem dieser App mit Android 11. 
Android 11 erlaubt den Dateizugriff nicht mehr so wie bisher, und die App, die ich in den Play Store geladen habe, um die Situation bei großem Speicherbedarf zu verbessern, durfte wg. Play Store Regeln nicht mehr im Kompatibilitätsmodus hochgeladen werden. 
RaMBLE-Import kann im Moment bei Android 11 nicht funktionieren, die App muss dafür verändert werden - siehe z.B. https://developer.android.com/about/versions/11/privacy/storage - und ich weiß im Moment noch nicht genau, wie es geht - trivial ist es jedenfalls nicht.

**Comment by Clysa** [comment]
Thanks für answering so quickly (and also for translating - didn't know I was supposed to write in English, sorry). Indeed, version 2.1.2 works and none of the two former problems occurs anymore. Great, thank you! And thank you, too, for developping this very useful app, I wouldn't want to be without anymore.

**Comment by FinnHuelsbusch** [comment]
This also helped me. 
Just one suggestion: Make it clear in the Release-Notes and the Readme. This would make it much easier for people to find this problem.

**Comment by mh-** [comment]
> Just one suggestion: Make it clear in the Release-Notes and the Readme. This would make it much easier for people to find this problem.

done.

**Comment by mh-** [comment]
Maybe you can now test https://github.com/mh-/corona-warn-companion-android/releases/2.2.0 please. This should work in Android 11, it implements the mandatory file picker --> you have to select the latest RaMBLE database file in the Downloads folder yourself.

**Comment by FinnHuelsbusch** [comment]
I can confirm it works.

**Comment by mh-** [comment]
(reopened, because the Play Store version is not yet published.)
