### ISSUE TITLE
[feature request] export matching results

### ISSUE THREAD

**Issue by r00t-** [mh-/corona-warn-companion-android#144]
could an option be added to export the results of matching, in any format?
(i found myself making screenshots and then using OCR to extract the data. :(  - for importing them into a script to match against gps logs.)
(kind of what is requested in #95, but i'd think a simple export is more within reach than processing location data internally, plus there's no standard for storing location logs anyway.)

(or maybe the matching code could be made available as a standalone program for non-interactive use - or maybe that exists already in some other project you can point me to?)

**Comment by mh-** [comment]
Well, before this app project, it all started with Python scripts:
https://github.com/mh-/diagnosis-keys
This https://github.com/mh-/en-android-readout is not public, but I can invite you.

**Comment by claudiuskastner** [comment]
I'd also be interested in these scripts if you don't mind :)
