### ISSUE TITLE
Slow matching of IDs compared to CWA or CCTG

### ISSUE THREAD

**Issue by ford--prefect** [mh-/corona-warn-companion-android#149]
ID matching in CWC takes **ages**, compared to the surprisingly quick matching in both the CWA or CCTG apps. Do they use a different algorithm? Is it worth and possible adapting this algorithm for the CWC as well?

rough benchmark:
Matching with 5660 collected IDs on 2022-01-12
CCTG: few seconds (hard to measure)
CWC: ~ 25 minutes

**Comment by mh-** [comment]
If you want to do benchmarking, here's what I've seen on a cheap Oukitel C16 Pro (MT6761P 2GHz Quad-core, 3GB RAM, Android 9): 
Set CWC to "1 day", which results in download of 322338 DKs (2022-01-11 and some hourly packages of 2022-01-12), matched with 4614 recorded RPIs -> 3 minutes 2 seconds.

The difference comes from two areas: 
1) The frameworks that CWA and CCTG use (Google Android Exposure Notifications Framework / microG) match with fewer downloaded DK packages, and cache the previous results. CWC will _not_ do that. The use case of CWC is not to warn users, but only to get details in case you have been warned by the other app - so there will be no background processing in CWC, and no storage of processed data. This makes my life a lot easier regarding e.g. security, privacy, the documentation and communication of this, and Google Play Store policies.
2) These frameworks use C++ and JNI for the actual matching, which is better suited for this task than the pure Java that CWC currently uses. PRs which improve CWC in this area will be welcome.

**Comment by ford--prefect** [comment]
Thanks for the explanation, I was neither aware of the caching in CWA/CCTG nor that they use optimized matching that is not easy to reuse here.
Good to have this documented.

**Comment by skyerjoe** [comment]
@mh-  
but cctg also provide some details over the encounters ( date/time) in newer versions. Or

**Comment by ford--prefect** [comment]
> @mh- but cctg also provide some details over the encounters ( date/time) in newer versions. Or

Can you elaborate? I'm using CCTG in version 2.14.1.1 and do not see any such feature nor is it [listed upstream](https://codeberg.org/corona-contact-tracing-germany/cwa-android/#what-is-the-difference-to-cwa).

**Comment by skyerjoe** [comment]
> I don't know, but if it does that now, why do you additionally need this app?
plain and simple 🙂
B/c no chart and no signal db  infos.

**Comment by skyerjoe** [comment]
> > @mh- but cctg also provide some details over the encounters ( date/time) in newer versions. Or
> 
> Can you elaborate? I'm using CCTG in version 2.14.1.1 and do not see any such feature nor is it [listed upstream](https://codeberg.org/corona-contact-tracing-germany/cwa-android/#what-is-the-difference-to-cwa).

It's hidden : " three dots" in the right upp corner - - - > "App-Informationen" - - - > tap down on the microg version ( greyed out) - - - - > "corona tracing"

That's it

**Comment by mh-** [comment]
FYI - I just opened **CCTG** after a few days, to check encounters - it also takes _ages_. 
I do **not** see a surprisingly quick matching in the CCTG app.

**Comment by ford--prefect** [comment]
As you pointed out in your first comment, there seems to be caching at work. And you also made clear why you don't want that, so this issue is actually solved for me (wontfix/notanissue).
