### ISSUE TITLE
Companion keeps downloading diagnosis keys

### ISSUE THREAD

**Issue by hman2** [mh-/corona-warn-companion-android#150]
Although the latest update did reduce the number of crashes, they still happen. And many times I have seen this: When the screensaver/lockscreen kicks in, after unlocking the phone, Companion either dies or goes only into background (yielding CCTG up front again). However, when you have Companion in the foreground again, Companion immediately starts to download all diagnosis keys (1,7 million today!) time and again. Each and every time. Why can't Companion simply use the keys it has already downloaded, and download only new diagnosis keys? Theoretically it is possible, albeit highly improbable that in one minute (many) news keys could have emerged. I do not see the need to download the bulk each and every time.

A crash of Companion would have significantly less impact if Companion would simply commence matching RPIs against DKs.

**Comment by mh-** [comment]
Have you tried setting the number of days to a lower number than 14?

**Comment by hman2** [comment]
Where is that setting? The only thing I can change is the list of countries...

With 1,7 million DK we urgently need load reduction mechanisms.  I already proposed that Companion could skip re-matching everything anew, by rememberin which RPI and which DK it has already checked? 

I haven't looked into Companion's code. But how do you match RPIs and DKs? Do you really inspect n(RPI) * n(DK)? That would, today, mean over a billion comparisons... Today I had nine unsuccessful runs of Companion. The best run came up to 88% (after half an hour of computing, while consuming 70% of the battery charge) and then it went into background, restarting anew after getting foreground focus.
Also, how do you compare? Is that written in high-level language like Java?

The storage delivered by CCTG export I guess is set as defined by CCTG. If I may ask: How is Companion's data storage? You won't have a full-fledged database like MySQL for that, but do you keep those data in one of those libraries that store in JSON but emulate SQL to the App? In SQL, comparing two IDs would simply be part of the SELECT, using the clause WHERE (ID.a = ID.b) thus leaving the entire computing to the DB (and DB can do that WAY faster than ANY high-level code possibly could), and you would only get those keys that do match, all others would not be delivered by the SELECT...

Thanks
hman

**Comment by AQbernhard** [comment]
Do you use version 2.3.1? 
With this version you can reduce the download by selection a number of days between 1 and 14. 
With this version my mobile can handle the whole amount of DKs
Regards
Bernhard

**Comment by hman2** [comment]
Hm, I have now upgraded to 2.3.1, thanks.

With a limit of 10 days (the peak almost always was at -12 days) still Companion goes into background, and upon getting focus again re-starts the download, and after that re-starts the matiching, and crashed at 10%...

**Comment by mh-** [comment]
I would like to explain the difference between the "days that are displayed", and the "days that are downloaded".

1. The "days that are displayed" refer to your calendar, when did you meet other people, when did risk encounters occur. These are the details that you are interested in when you use this app. 

2. The "days of key packages that are downloaded" refer to when infected users had positive tests and uploaded their Diagnosis Keys, and maybe one day later you can now download them. 
So the keys that you can download from 10 days ago can only come from users who had their test about 11 days ago. Those are not the most interesting keys today, you would better have downloaded them 10 days ago. 
If you really want / feel the need to use this app regularly, then set the Key Download value to 3, and open the app at least every 3 days. 

Does that make sense?

--- 

Ich möchte den Unterschied zwischen den "Tagen die angezeigt werden" und den "Tagen die heruntergeladen werden" erklären.

1. Die "angezeigten Tage" beziehen sich auf Deinen Kalender, wann hast Du andere Leute getroffen, wann sind Risikobegegnungen aufgetreten. Dies sind die Details, die Dich interessieren, wenn Du diese App verwendest. 

2. Die "Tage der heruntergeladenen Schlüsselpakete" beziehen sich darauf, dass infizierte Benutzer positive Tests hatten und ihre Diagnoseschlüssel hochgeladen haben, und vielleicht kannst Du sie einen Tag später herunterladen.
Die Schlüssel, die Du vor 10 Tagen herunterladen konntest, können also nur von Benutzern stammen, die ihren Test vor etwa 11 Tagen hatten. Das sind heute nicht die interessantesten Schlüssel, Du hättest sie besser vor 10 Tagen heruntergeladen.
Wenn Du diese App wirklich regelmäßig verwenden musst / möchtest, dann setze den Wert für den Schlüsseldownload auf 3 Tage und öffne die App mindestens alle 3 Tage.

Machen diese Erklärungen Sinn für Dich?

**Comment by skyerjoe** [comment]
According to this, i tried to compare the methods: 

14 days: 13 hits in 29.12.21
4 days:. 4 hits in 29.12.21 

How could I Interpret this

**Comment by mh-** [comment]
> According to this, i tried to compare the methods:
> 
> 14 days: 13 hits in 29.12.21 
> _**4**_ days: 4 hits in 29.12.21
> 
> How could I Interpret this

13-4 = 9 hits come from users who reported their test _**more than 4 days ago**_.
4 hits come from users who reported their test _**within the last 4 days**_.

**Comment by skyerjoe** [comment]
Ah OK

Yes makes sense that is the Timeline for reported cases not the date when u get in  contact with. I had mixed this up.

Thnx

**Comment by hman2** [comment]
Another observation: CCTG downloaded 183 MBytes since Nov. 10, 2021. Companion 4,75 GBytes since Nov. 11, 2021, so Companion downloaded 25times as many data as CCTG. That is due to it downloadind time and again every time it lost foreground, or crashed...
