### ISSUE TITLE
Dont understand these encounter matches.

### ISSUE THREAD

**Issue by skyerjoe** [mh-/corona-warn-companion-android#153]
```
M-PHONE:Xiaomi Mi9 T Pro ( not rooted) 
OS:     Mui Global 12.5.1 based on Android 11
SW:  	CCTG 2.14.1.3

```
I got some weird encounter matches. Which im not really understand

![Screenshot_2022-02-06-19-22-12-496_org tosl coronawarncompanion_2_cr](https://user-images.githubusercontent.com/1038130/152697327-fd62773e-7355-4e0b-bdd4-be7737753f54.png)

![Screenshot_2022-02-06-19-22-41-533_org tosl coronawarncompanion_2_cr_1](https://user-images.githubusercontent.com/1038130/152696823-37d91e03-4404-4eb2-b610-7c4ef996bdf7.png) ![Screenshot_2022-02-06-19-22-44-252_org tosl coronawarncompanion_2_cr_1](https://user-images.githubusercontent.com/1038130/152696826-06647280-795d-41aa-8429-6c06954fb520.png)

![Screenshot_2022-02-06-19-22-55-304_org tosl coronawarncompanion_2_cr](https://user-images.githubusercontent.com/1038130/152696990-afacd64f-4f9a-4f5b-8547-c19c4263b5ea.png) ![Screenshot_2022-02-06-19-22-57-944_org tosl coronawarncompanion_2_cr](https://user-images.githubusercontent.com/1038130/152696991-37184a4a-c7c9-4f71-aa25-975dccee6a41.png)

First for my understanding ( corect me if im wrong) , if some encounter is identified as an exposure risk every rpid's are getting concatenate together that the person which is infected is still traceable and wont be duplicated..  

But i got 2 Encounters on these Days. I think its an door to door contact cause the timeframes are really long. 

So if these 2 Persons which are infected or is this only 1 Person. 

best regards

**Comment by mh-** [comment]
It's probably only one person. If you change your phone's time zone to UTC, you will probably get only one result per day. The keys change around 0:00 UTC.

**Comment by skyerjoe** [comment]
But i thought the keys will be  still linked to the person which is infected they day before. 

So, why 2 different keys are appearing for the same Person. 

best regards

**Comment by mh-** [comment]
The keys are not linked across days. The days and the keys change at 0:00 UTC. 

If you are close to the same phone for 7 days, and set your phone to UTC, you will see 7 separate events. If you set another timezone, the app will show 14 separate events.

**Comment by skyerjoe** [comment]
ok got it , but then the report type has to be the same or ? 

and the symptome day onset doesnt really match if its the same person 
or did i miss sth. 

best regards

**Comment by skyerjoe** [comment]
No more relevant

Best regards
