### ISSUE TITLE
What is the "risk factor"?

### ISSUE THREAD

**Issue by wyrdforge** [mh-/corona-warn-companion-android#156]
Hi, 

I recently got a red notification from CWA.
CCTG running in parallel evaluates this as a low risk encounter.

I got 6 single ID contacts in a timespan of 40 minutes with 60 to 80 dB marked yellow and and green with a transmission risk of 6-8 in microCG (non-rooted). 

 These values do not make sense to me, esoecially when both apps show different interpretations of the same encounters.

Best regards

**Comment by mh-** [comment]
I do not fully understand your question, though. Is your quest related to the Companion App?

**Comment by wyrdforge** [comment]
Maybe it is just an interpretation issue, I have with the companion. I'll try to split up my overall problem a bit

I would assume, CCTG and CWA should gather similar data when used in parallel and should come to the same conclusion (which is not the case, but obviously not a companion issue) 

For the companion, the correlation of risk and damping factor is not obvious to me. The same damping factor is shown green(safe distance?), but yields a risk factor of 3 one time and 8 on a different encounter.

![Screenshot_20220216_221646_org tosl warnappcompanion](https://user-images.githubusercontent.com/19747300/154360566-414dbb60-dd7a-43bf-b3be-0eff1053a8b8.jpg)
![Screenshot_20220216_221731_org tosl warnappcompanion](https://user-images.githubusercontent.com/19747300/154360779-509f9933-5072-4aee-b1a3-c127e8be286e.jpg)

**Comment by mh-** [comment]
Ok. The "risk factor" is a property that belongs to the person who reported the infection and the day. It is not calculated by the companion app, just shown exactly as it was downloaded together with the particular Diagnosis Key. It could have been calculated in any way the CWA server currently pleases, I don't know what they currently do there. 

The two BLE recording apps use different frameworks, which use different strategies to sample and then keep records of the observed RPIs, that's probably why they yield different results.

**Comment by mh-** [comment]
I also changed the title of this issue, because the Companion app doesn't do warnings or risk calculations, just gives details on the data that warning apps have collected.

**Comment by wyrdforge** [comment]
Thanks for clarification. The fact, that the risk factor was not a "statistical" evaluation inside the companion, but a given metric from the main app was the missing link.

And while I'm here, many thanks for your efforts. Your software is a big help in assessing the real threat of all those warnings, you get nowadays :)
