### ISSUE TITLE
0 diagnosis keys downloaded

### ISSUE THREAD

**Issue by PalminX** [mh-/corona-warn-companion-android#33]
I installed WAC 1.3.0 on a device today, and initially did not have root access. 

Initially, WAC downloaded the diagnosis keys based on the country selection, and showed the statistics of the downloaded keys in the second graph.

I fiddled around with the Android system to get root access (using Magisk), and after that, WAC does not complain about missing root access anymore, but now, it doesn't show any diagnosis key downloads:

![image](https://user-images.githubusercontent.com/28887826/91552167-a76c9c80-e92b-11ea-8943-23bfe2f81dcf.png)

This is on a Samsung Galaxy A3 running Android 6.0.1. CWA has also been installed only today (i.e. does not yet have a risk assessment).

**Comment by mh-** [comment]
Ok, but this is expected. Now that the app sees your scanned RPIs, it only tries to download Diagnosis Keys for the days where it could find matches. Which in your case is only today. But the server doesn’t offer keys for today, the newest keys are yesterday’s keys. You will Keys tomorrow.

**Comment by PalminX** [comment]
Demo mode works fine

**Comment by PalminX** [comment]
> Ok, but this is expected. Now that the app sees your scanned RPIs, it only tries to download Diagnosis Keys for the days where it could find matches. Which in your case is only today. But the server doesn’t offer keys for today, the newest keys are yesterday’s keys. You will see keys tomorrow.

Ah, OK... that makes sense! Thanks for pointing this out!

**Comment by mh-** [comment]
But the text "Bitte warten..." should not be shown anymore when "Abgleich nicht möglich" is shown.

**Comment by PalminX** [comment]
> But the text "Bitte warten..." should not be shown anymore when "Abgleich nicht möglich" is shown.

This has disappeared now. Maybe when I switched modes?

**Comment by mh-** [comment]
And the code looks ok.
I guess I will close this.
