### ISSUE TITLE
Kein Link im Deutschen Play Store README

### ISSUE THREAD

**Issue by Atemu** [mh-/corona-warn-companion-android#43]
Es steht zwar drin, dass die App FOSS ist, aber nicht wo! :D

Die Repo hier zu finden benötigte erweitertes Google-fu.

**Comment by mh-** [comment]
Ja, das liegt daran, dass Google im Moment keine Referenz auf Corona im Play Store Text duldet :(

**Comment by Atemu** [comment]
Uff...

Könntest du dann vlt. dein GitHub profil angeben oder einen redirect hierher unter deiner Website/GH pages einstellen und die stattdessen ins README schreiben?

**Comment by mh-** [comment]
Ok, ich habe mal in der Play Console "(https://github.com/mh-)" hinzugefügt, müsste bald im Play Store sichtbar sein.
