### ISSUE TITLE
Belgium

### ISSUE THREAD

**Issue by pdehaye** [mh-/corona-warn-companion-android#55]
Modeled on the German one, so should be easy.

config: https://c19distcdn-prd.ixor.be/version/v1/configuration/country/BE/app_config
key example: https://c19distcdn-prd.ixor.be/version/v1/diagnosis-keys/country/BE/date/2020-10-07

**Comment by Snorkeldink** [comment]
I would like to also kindly request to add the support for Belgium as indeed it's just a fork of the German app. Thank you very much in advance.
