### ISSUE TITLE
support for microg Database

### ISSUE THREAD

**Issue by DO1JLR** [mh-/corona-warn-companion-android#57]
Hello

Since the latest [Release](https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.12.203315) microg now also offers an Exposure Notifications API for COVID-19 apps. But this seems to be incompatible with this app.

As you can see on the pictures [here](https://chaos.social/@l3d/105033064285055769), there is something wrong with the access. A smart person told me that microg uses a different database for this.

Is there a chance that this app will be extended with the microg database?
[.../ExposureDatabase.kt](https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureDatabase.kt)

Thanks :heart:

**Comment by mh-** [comment]
@DO1JLR the main issue with this is: I don’t have microG. But I think I could add this feature, if someone sent me a microG ExposureNotifications database `exposure.db` and the path where it can be copied from.

**Comment by DO1JLR** [comment]
I have no idea how to get the ``exposure.db``, but I would send you my database. 
Can you give me a hint how I can get access to it @mh- ?

**Comment by mh-** [comment]
Can you get a shell on that device and do `ls -l` and so on?

**Comment by DO1JLR** [comment]
Hello @mh- 

Please excuse the late reply. I had a problem with my mobile not storing exposure notifications. But the latest version of microg has solved this problem.

So here is my database. Found under [/data/data/com.google.android.gms/databases/exposure.db](https://github.com/mh-/corona-warn-companion-android/files/5391015/2020-10-16_exposure.zip).

**Comment by mh-** [comment]
Thanks. Do you need `su` to access this?

**Comment by DO1JLR** [comment]
Yes, I needed ``su``.

**Comment by mh-** [comment]
WTF are they doing with rssi?
```
rssi = ((rssi * duration) + (? * (? - timestamp - duration)) / (? - timestamp))
```
I get `-9223372036854775808` from the database

**Comment by mh-** [comment]
@DO1JLR See https://github.com/mh-/corona-warn-companion-android/tree/add-microg-mode

**Comment by mh-** [comment]
@DO1JLR Can you test on a real device?
[corona-warn-companion-github-debug.apk.zip](https://github.com/mh-/corona-warn-companion-android/files/5394546/corona-warn-companion-github-debug.apk.zip)

**Comment by DO1JLR** [comment]
Very very cool. The collected data is read excellently.

What doesn't quite work is the comparison with diagnostic keys. The app does not want to download any.

If I can help you with log data, let me know.
I have also stopped and restarted the app. Again, the app does not want to download any diagnostic keys.

![photo5211145462063673796](https://user-images.githubusercontent.com/16953664/96321319-4ac95c00-1015-11eb-9bef-aa6470a4f8f2.jpg)

**Comment by mh-** [comment]
Yes, it downloads. But only on 16.10. and there are 0 keys for that day.

**Comment by mh-** [comment]
I also got the feedback that microG will solve the RSSI bug: https://github.com/microg/android_packages_apps_GmsCore/issues/1230

**Comment by DO1JLR** [comment]
You were right @mh- , of course. Keys will be downloaded the next day. And it works wonderfully.

Thanks

![photo5213397261877358653](https://user-images.githubusercontent.com/16953664/96338629-da135580-108f-11eb-8960-b3ddda445f02.jpg "Screenshot corona-warn-companion App mit microg backend")

**Comment by mh-** [comment]
Adding a faked RPI also yielded the desired result:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/6257627/96349956-3fc50900-10b3-11eb-854a-dced49a4f2ce.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/6257627/96349960-4b183480-10b3-11eb-9ddd-03dcb9e5e1ab.png">
