### ISSUE TITLE
Incomplete time range in RaMBLE mode

### ISSUE THREAD

**Issue by ginkel** [mh-/corona-warn-companion-android#59]
I am using this app (v1.3.4) in RaMBLE mode. Despite exporting a current database from RaMBLE, the time range displayed in Warn Companion ends at 2020-10-12:

![image](https://user-images.githubusercontent.com/174129/96177558-5726b980-0f2e-11eb-887a-da4644ffbb34.png)

Any ideas?

P.S.: If that helps I could share the RaMBLE SQLite database, but would prefer to do so privately.

**Comment by mh-** [comment]
The RaMBLE databases are exported to the SD Card, and WAC looks for the one with the newest file name. What are the file names? And are you sure that you had recorded encounters on 13, 14, or 15 Oct.?

**Comment by mzielinskim** [comment]
I have the same problem. For me the recording ends on 12.10.2020 and yes i have records after that date in the database (i can see the last entries from 14.10. with the correct service id)

**Comment by mh-** [comment]
Strange, I just tried on my device, and I get a lot of entries from today. What are the file names on your SD Card that start with RaMBLE?

**Comment by mh-** [comment]
BTW if you want to send me something by e-mail: mh@tosl.org

**Comment by ginkel** [comment]
> The RaMBLE databases are exported to the SD Card, and WAC looks for the one with the newest file name. What are the file names? And are you sure that you had recorded encounters on 13, 14, or 15 Oct.?

```
blueline:/sdcard/Download $ ls -al *.sqlite
-rw-rw---- 1 root everybody 18153472 2020-10-14 15:42 RaMBLE_playstore_v40.15_20201014_1542.sqlite
-rw-rw---- 1 root everybody 19845120 2020-10-15 08:06 RaMBLE_playstore_v40.15_20201015_0806.sqlite
```

**Comment by ginkel** [comment]
> Could you delete all RaMBLE databases, export another one, and try again?

Done, didn't help. I sent you one of the problematic DBs by mail. IMO, it's quite large as there seems to be a lot of BT traffic around here.

**Comment by mh-** [comment]
ok,  with your databases, I can reproduce it. Let's see...
