### ISSUE TITLE
Handle BDADDR collisions (RaMBLE)

### ISSUE THREAD

**Issue by mh-** [mh-/corona-warn-companion-android#62]
RaMBLE uses the BDADDR of the beacon to determine whether the beacon has been seen before, and places all information with the same BDADDR into the same table row.
Random BDADDR are shorter and can therefore collide more often than RPIs.

A corresponding problem was reported by @uhengart in PR #56.

Own experiments show that RaMBLE updates the database table row when other service data (RPI) is received. So the RaMBLE database only contains the last seen RPI, but the `first_seen` field might correspond to an earlier sighting of a completely different device, that randomly chose the same BDADDR. 
Therefore we should handle the `first_seen` field with caution, maybe limit the duration to 30 minutes (backwards from `last_seen`), which would be slightly more than the maximum time between to BDADDR / RPI rotations.

**Comment by kbobrowski** [comment]
Does it mean that if there is BDADDR collision RaMBLE will override received RPI? This can lead to missed encounters?

**Comment by mh-** [comment]
@kbobrowski I think that would be the case, yes.

**Comment by kbobrowski** [comment]
It's very improbable, but would be interesting to put some number on it
