### ISSUE TITLE
Possibility to export Rolling Proximity IDs

### ISSUE THREAD

**Issue by Lionfox2** [mh-/corona-warn-companion-android#64]
It would be great to be able to export the rolling proximity ID. Espacially in the case you need to install a new ROM it would be great to still be warned in the case of a contact. Maybe it would be possible to export it and later import it in Ramble.

**Comment by mh-** [comment]
I'm not sure yet whether this should be in the scope of this app.

Meanwhile, if you want to export your RPIs and TEKs, they are located in these directories:
```
/data/data/com.google.android.gms/app_contact-tracing-contact-record-db/    # RPIs
/data/data/com.google.android.gms/app_contact-tracing-self-tracing-key-db/  # TEKs
```

 It's best to restore them in Recovery Mode, when GMS isn't trying to access them in parallel.

**Comment by Lionfox2** [comment]
Thanks a lot for the advice, searched all over the internet and didn't found the location of the RPIs!
