### ISSUE TITLE
Small question about the proto buffer export.bin diagnosis key download and the count displayed in graph (Belgium)

### ISSUE THREAD

**Issue by Snorkeldink** [mh-/corona-warn-companion-android#65]
Hello,

I'm a bit confused.

The latest graph from yesterday displayed 81 diagnosis keys downloaded on 19-10 when the file itself (linked below) contained 655 diagnosis keys. Similar discrepancies for the previous days where the number in the graph is substantially lower than the download file.  

https://c19distcdn-prd.ixor.be/version/v1/diagnosis-keys/country/BE/date/2020-10-19
https://c19distcdn-prd.ixor.be/version/v1/diagnosis-keys/country/BE/date/2020-10-18
https://c19distcdn-prd.ixor.be/version/v1/diagnosis-keys/country/BE/date/2020-10-17

Am I missing something obvious? 

![temp](https://user-images.githubusercontent.com/2566083/96565064-2c3cbc80-12c4-11eb-8df6-b1973b56530e.jpg)

Then debugging of the app itselfs shows:

D/org.tosl.coronawarncompanion.dkdownload.DKDownloadBelgium: Downloaded day: 2020-10-19
D/Unzip: Unzipped file. Length: 19751
D/DKDownloadUtils: Number of keys in this file: 655

Shouldn't the graph display 655 keys for 2020-10-19 but yet only displays 81?

Thanks to anyone helping :)

**Comment by mh-** [comment]
@Snorkeldink The graph shows the keys on the day when they were valid, so that you can compare each column with the day above and below. So, out of the 655, only 81 were for that day.

**Comment by Snorkeldink** [comment]
Thank you! I guess this just shows that very few people are actually using the Covid19 tracing app in Belgium unfortunately compared to the daily testing and incidence. Unfortunate.
