### ISSUE TITLE
Daylightsaving time related shifts

### ISSUE THREAD

**Issue by yanosz** [mh-/corona-warn-companion-android#71]
Is (for Germany)
* Encounters are shown in CET as of today
* E.g. an encountern on 2020-10-22, 21:15 is shown for 20:15 as of today.

Should (for Germany)
* Encounters should be shown in the the corresponding time zone (CEST <-> CET)

**Comment by mh-** [comment]
To clarify - 
the encounter happened in DST ("Summer" time), _before_ the switch from DST to Standard Time ("Summer" -> "Winter" time),
and now the app shows the timestamp as if it happened during Standard time ("Winter" time)?

**Comment by yanosz** [comment]
> To clarify -
> the encounter happened in DST ("Summer" time), _before_ the switch from DST to Standard Time ("Summer" -> "Winter" time),
> and now the app shows the timestamp as if it happened during Standard time ("Winter" time)?

correct.

**Comment by benlorenz** [comment]
I have the same observation, one encounter on 17/10 that was previously (before the switch) shown as 15:11. Now the same encounter shows 14:11 instead.

I am using microg mode (microg version 0.2.13).

**Comment by benlorenz** [comment]
Thanks! My encounter is back at 15:11.
