### ISSUE TITLE
Enhancement idea/request: Correlation with Google Maps Timeline/Takeout KML/JSON exports to display exposures approximate location

### ISSUE THREAD

**Issue by Snorkeldink** [mh-/corona-warn-companion-android#73]
Hi,

Unfortunately, there is no documented API for google Maps Timeline that can be queried directly by an app.

However the Google maps timeline (whole) history can be downloaded through Google takeout (JSON or KML format). 
And individual days can be downloaded directly on the timeline web interface by selecting a specific day and exporting (KML format only).

Another user made use of the second functionality to actually download the Maps timeline history using the second option (daily KML) on https://github.com/alexattia/Maps-Location-History (also see for more details https://janlauge.github.io/2017/extracting-location-history/).

So I have two enhancements ideas:

1. Wouldn't it be possible/interesting to add a KML import functionality (manual) that would allow pinpointing exposure location within the app? 

2. Similarly, wouldn't it be possible to use the previously mentioned github script to automate the process within the app and get approximate exposure geolocation? 

Best Regards

**Comment by mh-** [comment]
Hi @Snorkeldink, 

thank you very much for your suggestion.
While I understand that this would be interesting to many users, I decided to _not_ pursue this path, for two reasons:
- The main reason is that I do not want to make this app appear as if it would easily be used to identify infected persons.
- Another reason is that this would add a lot of complexity and maintenance.

Best regards
Michael

**Comment by Snorkeldink** [comment]
Thank you. Well I guess it's probably a wise decision as this would indeed probably cause privacy issues and attract unwanted attention. Better to not have this feature. Closing.
