### ISSUE TITLE
No matching RPI in contact records, despite having an exposure result

### ISSUE THREAD

**Issue by benjeffery** [mh-/corona-warn-companion-android#75]
Apologies that my question is not about the app directly, but hoping you can help.

On my phone there is an exposure warning entry in `exposure-result-storage-db` but none of the RPI keys in `contact-tracing-contact-record-db` match a `diagnosis_key` from `app_en_diagnosis_keys`. 

Is it possible the entries are removed after the exposure result is created? Or have I missed something?

**Comment by mh-** [comment]
@benjeffery by _not matching_, do you refer to a byte-by-byte match of Diagnosis Key vs. RPI (that wouldn't work),
or did you generate RPIs from the Diagnosis Keys? Which tool did you use for this?

**Comment by benjeffery** [comment]
Ah-ha! Thanks, I was doing a byte-by-byte, will lookup how to convert. It's a script I threw together myself when I got an alert, as the UK app says nothing about when, or for how long you were exposed and I wanted to know.

Still learning how everything fits together, your code here has been invaluable, so many thanks.

**Comment by kbobrowski** [comment]
@benjeffery we are not supporting UK yet in companion app, although should be quite easy to extend it as it was done for other countries. Maybe a nice feature would also be to source Diagnosis Keys from internal database of GMS? Then it would be automatically work in every country.

You can also use https://kbobrowski.github.io/covid-exposure/ which is a simple matching engine which needs to be fed manually with Diagnosis Keys .zip file and Bluetooth data in protobuf format

**Comment by benjeffery** [comment]
Many thanks for the pointers, as usual I should have read all the docs! I don't have root, so am working off files copied via the boot loader. I'll try using that link - looks useful!

**Comment by benjeffery** [comment]
@kbobrowski I got your site to work, thanks so much. It really helped me and now I don't have to worry! :heart:

**Comment by kbobrowski** [comment]
@benjeffery glad to hear that!
