### ISSUE TITLE
Feature request: fine-grained non-infectious contact statistics

### ISSUE THREAD

**Issue by blaueente** [mh-/corona-warn-companion-android#77]
There is a graph with total contacts per day.
It would be nice to have a more fine-grained graph when exactly these (harmless) contacts happen.
This can be used to get a better estimate for risk for specific activities, to optimize contact-reduction.
For example, one has a day with many overall contacts, but one is not sure if this is due to harmless bluetooth going through walls from one of the neighbours' apartments, or, how many of one's contacts happen in the commute with public transport vs. actually in the workplace. 
The most straightforward implementation would probably be: if a bar is clicked in the daily bar graph, just show the same sub-view for all daily contacts as for the infectious exposure contacts.

**Comment by mh-** [comment]
Dear @blaueente,
Thank you for your suggestion.
However, when I started this project some time ago, I discussed the privacy implications with many people. At that time, I decided to not offer details about contacts, unless that would help better understand a risk notification about a match with a Diagnosis Key.
What you want to achieve could however be done by using RaMBLE and its filter options.
Cheers
Michael
