### ISSUE TITLE
CWCA stopped processing RaMBLE encounters since 2020-11-01

### ISSUE THREAD

**Issue by ginkel** [mh-/corona-warn-companion-android#78]
Hi there,

current CWCA, v1.3.9, apparently stopped processing encounters from RaMBLE since 2020-11-01 despite a current RaMBLE database export. If you need my RaMBLE database to investigate further, please let me know and I'll drop you a mail.

Thanks,
Thilo

**Comment by mh-** [comment]
Hi @ginkel 
Sorry, I don't understand, what exactly do you mean with "stopped processing"?
This is how my screen looks in RaMBLE mode:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/6257627/97813450-a8ea7600-1c88-11eb-8bcf-f3ba0e3947da.png">
Thanks
Michael

**Comment by ginkel** [comment]
Hi @mh-,

despite a current RaMBLE database export, my screen currently looks like this (i.e., all of today's encounters [and probably also some of yesterday's] seem to be ignored):

![image](https://user-images.githubusercontent.com/174129/97813596-6ecda400-1c89-11eb-9086-a71837b05756.png)

Regards,
Thilo

**Comment by ginkel** [comment]
Just noticed: While RaMBLE shows up as active through its notification it stopped capturing. :-/ Sorry for the false positive, CWCA is working correctly.

I was wondering whether it would make sense to include a BLE scanner that is more reliable with CWCA. Any thoughts?

**Comment by kbobrowski** [comment]
@ginkel I have BLE scanner based on Raspberry Pi which solves RaMBLE issues, works 24/7 and stores scan results in local DB with REST endpoint. Using online matching tool for it at the moment - https://kbobrowski.github.io/covid-exposure/, perhaps we could include an option to import the format I use for it in Companion app.

PS. it may be convenient to discuss this over Slack, https://covidapps.herokuapp.com/ channel #companion-app

**Comment by skyerjoe** [comment]
is this issue still resolved ? 

best regards

**Comment by mh-** [comment]
@skyerjoe I believe the problem was solved. Or do you currently have a problem with RaMBLE?

**Comment by ginkel** [comment]
For me it was a PEBKAC-style issue... ;-)

**Comment by skyerjoe** [comment]
to be honest, i havent undestand the issue , i thought it was an general problem that ramble doesnt capture when cwca is running, ( i cannot prove interplay between both  completley i have no DB with matching keys just my own scanned ones )  
sorry for confusion
iv'e donwloaded the last apk version and everything seems to runs smoothly 

best regards

**Comment by mh-** [comment]
@skyerjoe ok - no, this app does not interfere with RaMBLE at all. It just reads the newest exported database from the SD card.  Some time ago we had a bug that prevented this database reading in some circumstances, but that’s fixed.
