### ISSUE TITLE
Add info about Denmark, Latvia and Spain

### ISSUE THREAD

**Issue by mh-** [mh-/corona-warn-companion-android#86]
because they are now part of the CWA server Diagnosis Key distribution

**Comment by kbobrowski** [comment]
Are we sure though that other countries are also implementing "One Europe" approach? I guess this is the most probable scenario, but a country can also decide to allow user to select "visited countries"

**Comment by mh-** [comment]
That would exclude keys from the German distribution if a user selected that they didn't visit Germany, right? 
Which should be ok, I think.

**Comment by kbobrowski** [comment]
@mh- the problem is that if let's say Denmark is implementing interoperability mode with selecting visited countries, then WAC user living in Denmark will only see encounters with people who visited Germany

**Comment by mh-** [comment]
That's true. If we knew which mode the countries use, we could implement separate download options for those that don't use _One Europe_ (and allow Diagnosis Keys download).
