### ISSUE TITLE
Crash immediately after opening

### ISSUE THREAD

**Issue by not-a-feature** [mh-/corona-warn-companion-android#88]
First of all, thank you very much for this app, it was several times very helpfull. :beers: 

## Describe the bug
After opening the App a second time it crashes immeadiately. 
If I clear the App's data, i can open it and use all functions, a second-time wont work.

## Expected behaviour
The app shouldn't crash.

## Steps to reproduce the issue
1. Install the App
2. Open & use it
3. Close the app completly
4. Reopen it -> Crash
5. Delete App data
6. Go to step 2

### Device
- Motorola Moto G7 Play
- LineageOS 17.1, based on Android 10 
- SU: Magisk 20.4 with Magisk Manager 8
### CrashLog
I get a nullpointer-exception in line 337 in the Source Class `org.osmdroid.config.DefaultConfiguratonProvider`.
This leads to a runtime-exception: Unable to start activity `ComponentInfo{MainActivity}`

**Comment by not-a-feature** [comment]
Closing the issue as it's fixed in the latest version.

**Comment by mh-** [comment]
Very good bug description, though!
