### ISSUE TITLE
Error - No encounters could be extracted

### ISSUE THREAD

**Issue by hackfix** [mh-/corona-warn-companion-android#92]
Hi,

when opening the app I get the following error:
```
No encounters could be extracted.
Are Exposure Notifications enabled?
Did you grant ROOT rights to this app?
```

My device is rooted and root rights were granted to this app.
Other apps that require root rights are working without any problems

What could be the cause of this?

Thanks
Hackfix

**Comment by mh-** [comment]
Hi @hackfix 
Could you please check the result of 
```
adb shell
su
ls -l /data/data/com.google.android.gms/app_contact-tracing-contact-record-db/ 
```

That's where the app tries to find the database.

**Comment by hackfix** [comment]
@mh- 

Thank you for the reply.
No problem. Here's the output:
```
-rw------- 1 u0_a32 u0_a32   0 2020-11-16 08:36 004338.log
-rw------- 1 u0_a32 u0_a32  16 2020-11-16 08:36 CURRENT
-rw------- 1 u0_a32 u0_a32   0 2020-06-16 16:20 LOCK
-rw------- 1 u0_a32 u0_a32 178 2020-11-16 08:36 LOG
-rw------- 1 u0_a32 u0_a32 178 2020-11-15 08:34 LOG.old
-rw------- 1 u0_a32 u0_a32 111 2020-11-16 08:36 MANIFEST-004337
```

**Comment by mh-** [comment]
Strange, the size is really small, and there's no `.ldb` file. 
When did you activate Exposure Notifications (i.e. activated the Corona-Warn-App)? 
Maybe the Google Exposure Notifications framework did not collect any RPIs yet?
