### ISSUE TITLE
App kann nicht im Root oder Ramble Modus betrieben werden 

### ISSUE THREAD

**Issue by SinaLudwig** [mh-/corona-warn-companion-android#94]
Hallo,
Die Probleme liegen wohl hauptsächlich an meinem technischen Unvermögen. 
1. Wie das mit dem Root-Modus funktioniert, weiß ich nicht. (Samsung Galaxy S10 lite) Man hört immer nur, dass man das als Laie nicht tun soll.
2. Ich habe eine Datei aus den Google-Überprüfungen exportiert. Ob das die richtige ist, weiß ich nicht. Wo ich sie ablegen muss, damit es funktioniert, wird auch nirgends beschrieben. Zumindest habe ich nichts dazu gefunden. Und die App findet die exportierte Liste auch nicht.

Wenn man es weiß, vermutlich ganz einfach zu lösen, aber als "einfacher" User nicht so trivial.

**Comment by mh-** [comment]
Also das mit RaMBLE funktioniert so:
Man installiert eine weitere App, nämlich "RaMBLE": https://play.google.com/store/apps/details?id=com.contextis.android.BLEScanner
Diese App zeichnet dann die Begegnungen (incl. Zeit und Ort) auf, man muss dazu oben auf das Dreieck tippen.
Dann kann man am nächsten Tag in der RaMBLE oben rechts auf "Datenbank exportieren" tippen, und dann kann die Warn App Companion App diese Datenbank einlesen.

Ist leider nur ein Kompromiss, RaMBLE verbraucht Akku-Leistung, und manchmal hört RaMBLE auch von alleine mit der Aufzeichnung auf, und man muss immer von Hand exportieren, aber anders geht es leider nicht.

**Comment by SinaLudwig** [comment]
Ok, Dankeschön.
Und das mit dem Root?

**Comment by mh-** [comment]
Da gibt es Anleitungen, aber für Laien ist es eher nichts.

**Comment by SinaLudwig** [comment]
Ok, vielen Dank für die Hilfe. Dann versuche ich es mal mit ramble
