### ISSUE TITLE
Request: Add support for Corona Contact Tracing Germany

### ISSUE THREAD

**Issue by m-rey** [mh-/corona-warn-companion-android#98]
Corona Contact Tracing Germany (CCTG), a CWA fork without proprietary dependencies, has been released: https://codeberg.org/corona-contact-tracing-germany/cwa-android/releases

It would be nice if the Corona-Warn-Companion App would also support getting its information from CCTG, like it already does with CWA.

**Comment by mh-** [comment]
Hi @m-rey, CCTG-cwa-android seems to use microG, and the Corona-Warn-Companion app can already import the database from microG. Did you try this?

**Comment by m-rey** [comment]
I'm currently not using microG, so I'm unable to test if it works. I guess it should?

Nevertheless, CCTG can also run without microG:
> If there's microg already installed on the system it will use the exposure notification framework from there. Otherwise it will use the bundled implementation. It will never connect to the play services exposure notification framework.

 source: https://codeberg.org/corona-contact-tracing-germany/cwa-android/src/branch/main/README.md#corona-contact-tracing-germany

**Comment by mh-** [comment]
Ok, I hope the CCTG contributors will clarify this: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/11

**Comment by hackfix** [comment]
Are there any plans to support CCTG in the near future?
thanks!

**Comment by mh-** [comment]
@hackfix in principle: yes,
but: it's not clear to me whether CCTG will support this: https://github.com/mh-/corona-warn-companion-android/pull/97 - and then the `singleTask` launch mode seems to be a problem.
The other option would be to add a "CCTG Mode" to WAC, which can easily be done but would require root access.

I don't know much about CCTG and the context in which users run the app (Android with Google Mobile Services, microG, ...?) 
Can users of CCTG easily give root access, or is that a problem?

**Comment by hackfix** [comment]
sounds good :)

In my case I can easily give root access.
Since CCTG is not available in Playstore and have to be installed via alternative ways I guess most users have at least a root access and are also not running the stock rom.

**Comment by KaratekHD** [comment]
I just forked this repository and started working on this. Will probably open a pull request soon.

**Comment by hackfix** [comment]
Awesome - you guy did a great job!

**Comment by KaratekHD** [comment]
> Awesome - you guys did a great job!

Thanks!
